NO-ISSUE: Update current-version script
Use the --always and --first-parent flags and error if tag could
not be generated still.

Also ensure that we only choose tags that start with 'v' to exclude
other types of tags such as helm chart tags.

diff --git a/hack/current-version b/hack/current-version
--- a/hack/current-version
+++ b/hack/current-version
@@ -7,10 +7,15 @@ git config --global --add safe.directory "$(pwd)" 2>/dev/null || true
 # Prefer proper release tags pointing at this exact commit first, prioritizing the highest version
 # tag. If there is no tag at this commit, then fallback to 'git describe' which will construct a
 # "human-readable" artificial tag.
-tag=$(git -c "versionsort.suffix=-rc" tag --points-at HEAD --sort version:refname | tail -n 1 2>/dev/null)
+tag=$(git -c "versionsort.suffix=-rc" tag --points-at HEAD --sort version:refname -l 'v*' | tail -n 1 2>/dev/null)
 
 if [[ -z "$tag" ]]; then
-  tag=$(git describe --tags --exclude latest 2>/dev/null || echo -n "v0.0.0-unknown")
+  tag=$(git describe --tags --always --first-parent --match 'v*' 2>/dev/null)
+fi
+
+if [[ -z "$tag" ]]; then
+  echo "ERROR: Unable to generate tag from repo" >&2
+  exit 1
 fi
 
 echo -n "$tag"
